const contexts = {
    AEP_CONTEXT: "aepContext",
    ACCOUNT_CONTEXT: "accountContext",
    CHANGED_PRODUCTS_CONTEXT: "changedProductsContext",
    CATEGORY_CONTEXT: "categoryContext",
    CUSTOM_URL_CONTEXT: "customUrlContext",
    DATA_SERVICES_EXTENSION_CONTEXT: "dataServicesExtensionContext",
    DEBUG_CONTEXT: "debugContext",
    EVENT_FORWARDING_CONTEXT: "eventForwardingContext",
    EXPERIENCE_PLATFORM_CONNECTOR_EXTENSION_CONTEXT: "experiencePlatformConnectorExtensionContext",
    MAGENTO_EXTENSION_CONTEXT: "magentoExtensionContext",
    ORDER_CONTEXT: "orderContext",
    ORDER_PAGE_CONTEXT: "orderPageContext",
    PAGE_CONTEXT: "pageContext",
    PRODUCT_CONTEXT: "productContext",
    RECOMMENDATIONS_CONTEXT: "recommendationsContext",
    RECOMMENDATIONS_EXTENSION_CONTEXT: "recommendationsExtensionContext",
    REFERRER_URL_CONTEXT: "referrerUrlContext",
    REQUISITION_LIST_CONTEXT: "requisitionListContext",
    REQUISITION_LIST_ITEMS_CONTEXT: "requisitionListItemsContext",
    SEARCH_EXTENSION_CONTEXT: "searchExtensionContext",
    SEARCH_INPUT_CONTEXT: "searchInputContext",
    SEARCH_RESULTS_CONTEXT: "searchResultsContext",
    SHOPPER_CONTEXT: "shopperContext",
    SHOPPING_CART_CONTEXT: "shoppingCartContext",
    STOREFRONT_INSTANCE_CONTEXT: "storefrontInstanceContext",
} as const;

export default contexts;
