name: publish-latest

on:
    push:
        branches: [main]
        tags:
            - "v*"

jobs:
    publish-latest:
        name: publish-latest
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}

            # - name: cache
            #   uses: actions/cache@v2
            #   with:
            #       path: "**/node_modules"
            #       key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}                  

            - name: node
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - name: install
              run: yarn install --frozen-lockfile

            - name: build
              run: yarn build --filter="@adobe/magento*"

            - name: publish storefront sdk
              working-directory: ./packages/storefront-events-sdk
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}

            - name: publish storefront collector
              working-directory: ./packages/storefront-events-collector
              run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}                  
