name: pull-request

on:
    pull_request:
        branches:
            - main

jobs:
    pull_request:
        name: pull-request
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [lts/-n, lts/*]
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}

            - name: cache
              uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

            - name: node ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn lint
            - run: yarn test
